export POWERLINE_ZSH='/usr/lib/python3.4/site-packages/powerline/bindings/zsh/powerline.zsh'
export TERM=xterm-256color
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME='agnoster'
export DEFAULT_USER=$USER
export CLICOLOR=1
export GREP_OPTIONS='--color=auto'

source $POWERLINE_ZSH
source $ZSH/oh-my-zsh.sh

unset RPROMPT

eval `dircolors ~/.dircolors`

alias mkdir='mkdir -pv'
alias cp='cp -v'
alias mv='mv -v'
